# -*- coding: utf-8 -*-
"""ScrapsMT_CL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12YyRVJz4XaCkRbPi114DYcFcjRZMCcz0
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url = 'https://www.wikiexplora.com/Monta%C3%B1a_Chile'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')

data = []
for link in soup.find_all('a'):
    data.append(str(link.get('href')))

len(data)

filtro_1 = []
for word in data:
    if word.startswith('/'):
        filtro_1.append(word)

len(filtro_1)
print(filtro_1)

test = filtro_1.index('/Cerro_Douglas_Tompkins')
print(test)

filtro_2 = filtro_1[0:321]
print(filtro_2)

filtro_3 = []
for word in filtro_2:
    if word.startswith('/Trekking'):
        filtro_3.append(word)

filtro_4 = [e for e in filtro_2 if e not in filtro_3]

filtro_5 = []
for word in filtro_4:
    if word.startswith('/Especial'):
        filtro_5.append(word)

filtro_final = [e for e in filtro_4 if e not in filtro_5]

"""Hay un total de 289 rutas de montañismo disponibles desde la web"""

len(filtro_final)

link = 'https://www.wikiexplora.com'
link + filtro_final[0]

Base = ['Actividad','Ubicación', 'Belleza', 'Atractivos',
       'Duración', 'Exigencia física','Sendero', 'Señalización',
       'Infraestructura', 'Topología', 'Altitud',
       'Distancia (k)', 'Altitud media']

df = pd.DataFrame(columns = Base)
df

url = link + filtro_final[0]
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html.parser')
nombre = filtro_final[0]
tabla = soup.find('table', class_ = "infobox")


header = []
rows = []
for i, row in enumerate(tabla.find_all('tr')):
    if i == 0:
        header = [el.text.strip() for el in row.find_all('th')]
    else:
        rows.append([el.text.strip() for el in row.find_all('td')])


flat_list = [item for sublist in rows for item in sublist]
flat_list = [x for x in flat_list if x != '']
flat_list = [s.replace('\xa0', ' ') for s in flat_list]
flat_list = flat_list[:13]

df.loc['0', :] = flat_list
df['Nombre'] = nombre
df

for idx, nombre in enumerate(filtro_final[:100]):
    url = link + nombre
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')
    tabla = soup.find('table', class_="infobox")

    if tabla:
        header = []
        rows = []

        for i, row in enumerate(tabla.find_all('tr')):
            if i == 0:
                header = [el.text.strip() for el in row.find_all('th')]
            else:
                rows.append([el.text.strip() for el in row.find_all('td')])

        flat_list = [item for sublist in rows for item in sublist]
        flat_list = [x for x in flat_list if x != '']
        flat_list = [s.replace('\xa0', ' ') for s in flat_list]
        flat_list = flat_list[:13]
        flat_list.append(nombre)

        df.loc[idx, :] = flat_list

df